#ifndef SCREEN_IDS_H
#define SCREEN_IDS_H

#define BOOT_SCREEN_GOUP_ID 0
#define BOOT_SCREEN_ID 1
#define BOOT_SCREEN_EXIT_ID 2

#define PLANT_STATS_SCREEN_GROUP_ID 3
#define PLANT_TEMP_SCREEN_ID 4
#define PLANT_MOISTURE_SCREEN_ID 5

#define SETTINGS_SCREEN_GROUP_ID 6
#define INFO_SCREEN_ID 7
#define PING_SCREEN_ID 8

#define SLEEP_SCREEN_GROUP_ID 9
#define SLEEP_SCREEN_ID 10

#endif
